INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (1, 'Quận Ba Đình', '001', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (2, 'Quận Hoàn Kiếm', '002', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (3, 'Quận Tây Hồ', '003', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (4, 'Quận Long Biên', '004', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (5, 'Quận Cầu Giấy', '005', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (6, 'Quận Đống Đa', '006', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (7, 'Quận Hai Bà Trưng', '007', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (8, 'Quận Hoàng Mai', '008', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (9, 'Quận Thanh Xuân', '009', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (10, 'Huyện Sóc Sơn', '016', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (11, 'Huyện Đông Anh', '017', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (12, 'Huyện Gia Lâm', '018', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (13, 'Quận Nam Từ Liêm', '019', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (14, 'Huyện Thanh Trì', '020', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (15, 'Quận Bắc Từ Liêm', '021', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (16, 'Thành phố Hà Giang', '024', 'Thành phố', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (17, 'Huyện Đồng Văn', '026', 'Huyện', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (18, 'Huyện Mèo Vạc', '027', 'Huyện', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (19, 'Huyện Yên Minh', '028', 'Huyện', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (20, 'Huyện Quản Bạ', '029', 'Huyện', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (21, 'Huyện Vị Xuyên', '030', 'Huyện', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (22, 'Huyện Bắc Mê', '031', 'Huyện', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (23, 'Huyện Hoàng Su Phì', '032', 'Huyện', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (24, 'Huyện Xín Mần', '033', 'Huyện', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (25, 'Huyện Bắc Quang', '034', 'Huyện', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (26, 'Huyện Quang Bình', '035', 'Huyện', '02');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (27, 'Thành phố Cao Bằng', '040', 'Thành phố', '04');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (28, 'Huyện Bảo Lâm', '042', 'Huyện', '04');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (29, 'Huyện Bảo Lạc', '043', 'Huyện', '04');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (30, 'Huyện Hà Quảng', '045', 'Huyện', '04');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (31, 'Huyện Trùng Khánh', '047', 'Huyện', '04');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (32, 'Huyện Hạ Lang', '048', 'Huyện', '04');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (33, 'Huyện Quảng Hòa', '049', 'Huyện', '04');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (34, 'Huyện Hoà An', '051', 'Huyện', '04');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (35, 'Huyện Nguyên Bình', '052', 'Huyện', '04');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (36, 'Huyện Thạch An', '053', 'Huyện', '04');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (37, 'Thành Phố Bắc Kạn', '058', 'Thành phố', '06');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (38, 'Huyện Pác Nặm', '060', 'Huyện', '06');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (39, 'Huyện Ba Bể', '061', 'Huyện', '06');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (40, 'Huyện Ngân Sơn', '062', 'Huyện', '06');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (41, 'Huyện Bạch Thông', '063', 'Huyện', '06');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (42, 'Huyện Chợ Đồn', '064', 'Huyện', '06');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (43, 'Huyện Chợ Mới', '065', 'Huyện', '06');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (44, 'Huyện Na Rì', '066', 'Huyện', '06');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (45, 'Thành phố Tuyên Quang', '070', 'Thành phố', '08');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (46, 'Huyện Lâm Bình', '071', 'Huyện', '08');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (47, 'Huyện Na Hang', '072', 'Huyện', '08');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (48, 'Huyện Chiêm Hóa', '073', 'Huyện', '08');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (49, 'Huyện Hàm Yên', '074', 'Huyện', '08');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (50, 'Huyện Yên Sơn', '075', 'Huyện', '08');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (51, 'Huyện Sơn Dương', '076', 'Huyện', '08');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (52, 'Thành phố Lào Cai', '080', 'Thành phố', '10');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (53, 'Huyện Bát Xát', '082', 'Huyện', '10');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (54, 'Huyện Mường Khương', '083', 'Huyện', '10');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (55, 'Huyện Si Ma Cai', '084', 'Huyện', '10');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (56, 'Huyện Bắc Hà', '085', 'Huyện', '10');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (57, 'Huyện Bảo Thắng', '086', 'Huyện', '10');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (58, 'Huyện Bảo Yên', '087', 'Huyện', '10');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (59, 'Thị xã Sa Pa', '088', 'Thị xã', '10');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (60, 'Huyện Văn Bàn', '089', 'Huyện', '10');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (61, 'Thành phố Điện Biên Phủ', '094', 'Thành phố', '11');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (62, 'Thị Xã Mường Lay', '095', 'Thị xã', '11');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (63, 'Huyện Mường Nhé', '096', 'Huyện', '11');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (64, 'Huyện Mường Chà', '097', 'Huyện', '11');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (65, 'Huyện Tủa Chùa', '098', 'Huyện', '11');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (66, 'Huyện Tuần Giáo', '099', 'Huyện', '11');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (67, 'Huyện Điện Biên', '100', 'Huyện', '11');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (68, 'Huyện Điện Biên Đông', '101', 'Huyện', '11');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (69, 'Huyện Mường Ảng', '102', 'Huyện', '11');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (70, 'Huyện Nậm Pồ', '103', 'Huyện', '11');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (71, 'Thành phố Lai Châu', '105', 'Thành phố', '12');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (72, 'Huyện Tam Đường', '106', 'Huyện', '12');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (73, 'Huyện Mường Tè', '107', 'Huyện', '12');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (74, 'Huyện Sìn Hồ', '108', 'Huyện', '12');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (75, 'Huyện Phong Thổ', '109', 'Huyện', '12');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (76, 'Huyện Than Uyên', '110', 'Huyện', '12');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (77, 'Huyện Tân Uyên', '111', 'Huyện', '12');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (78, 'Huyện Nậm Nhùn', '112', 'Huyện', '12');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (79, 'Thành phố Sơn La', '116', 'Thành phố', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (80, 'Huyện Quỳnh Nhai', '118', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (81, 'Huyện Thuận Châu', '119', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (82, 'Huyện Mường La', '120', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (83, 'Huyện Bắc Yên', '121', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (84, 'Huyện Phù Yên', '122', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (85, 'Huyện Mộc Châu', '123', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (86, 'Huyện Yên Châu', '124', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (87, 'Huyện Mai Sơn', '125', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (88, 'Huyện Sông Mã', '126', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (89, 'Huyện Sốp Cộp', '127', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (90, 'Huyện Vân Hồ', '128', 'Huyện', '14');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (91, 'Thành phố Yên Bái', '132', 'Thành phố', '15');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (92, 'Thị xã Nghĩa Lộ', '133', 'Thị xã', '15');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (93, 'Huyện Lục Yên', '135', 'Huyện', '15');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (94, 'Huyện Văn Yên', '136', 'Huyện', '15');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (95, 'Huyện Mù Căng Chải', '137', 'Huyện', '15');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (96, 'Huyện Trấn Yên', '138', 'Huyện', '15');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (97, 'Huyện Trạm Tấu', '139', 'Huyện', '15');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (98, 'Huyện Văn Chấn', '140', 'Huyện', '15');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (99, 'Huyện Yên Bình', '141', 'Huyện', '15');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (100, 'Thành phố Hòa Bình', '148', 'Thành phố', '17');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (101, 'Huyện Đà Bắc', '150', 'Huyện', '17');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (102, 'Huyện Lương Sơn', '152', 'Huyện', '17');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (103, 'Huyện Kim Bôi', '153', 'Huyện', '17');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (104, 'Huyện Cao Phong', '154', 'Huyện', '17');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (105, 'Huyện Tân Lạc', '155', 'Huyện', '17');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (106, 'Huyện Mai Châu', '156', 'Huyện', '17');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (107, 'Huyện Lạc Sơn', '157', 'Huyện', '17');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (108, 'Huyện Yên Thủy', '158', 'Huyện', '17');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (109, 'Huyện Lạc Thủy', '159', 'Huyện', '17');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (110, 'Thành phố Thái Nguyên', '164', 'Thành phố', '19');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (111, 'Thành phố Sông Công', '165', 'Thành phố', '19');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (112, 'Huyện Định Hóa', '167', 'Huyện', '19');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (113, 'Huyện Phú Lương', '168', 'Huyện', '19');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (114, 'Huyện Đồng Hỷ', '169', 'Huyện', '19');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (115, 'Huyện Võ Nhai', '170', 'Huyện', '19');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (116, 'Huyện Đại Từ', '171', 'Huyện', '19');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (117, 'Thị xã Phổ Yên', '172', 'Thị xã', '19');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (118, 'Huyện Phú Bình', '173', 'Huyện', '19');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (119, 'Thành phố Lạng Sơn', '178', 'Thành phố', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (120, 'Huyện Tràng Định', '180', 'Huyện', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (121, 'Huyện Bình Gia', '181', 'Huyện', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (122, 'Huyện Văn Lãng', '182', 'Huyện', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (123, 'Huyện Cao Lộc', '183', 'Huyện', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (124, 'Huyện Văn Quan', '184', 'Huyện', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (125, 'Huyện Bắc Sơn', '185', 'Huyện', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (126, 'Huyện Hữu Lũng', '186', 'Huyện', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (127, 'Huyện Chi Lăng', '187', 'Huyện', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (128, 'Huyện Lộc Bình', '188', 'Huyện', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (129, 'Huyện Đình Lập', '189', 'Huyện', '20');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (130, 'Thành phố Hạ Long', '193', 'Thành phố', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (131, 'Thành phố Móng Cái', '194', 'Thành phố', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (132, 'Thành phố Cẩm Phả', '195', 'Thành phố', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (133, 'Thành phố Uông Bí', '196', 'Thành phố', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (134, 'Huyện Bình Liêu', '198', 'Huyện', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (135, 'Huyện Tiên Yên', '199', 'Huyện', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (136, 'Huyện Đầm Hà', '200', 'Huyện', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (137, 'Huyện Hải Hà', '201', 'Huyện', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (138, 'Huyện Ba Chẽ', '202', 'Huyện', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (139, 'Huyện Vân Đồn', '203', 'Huyện', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (140, 'Thị xã Đông Triều', '205', 'Thị xã', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (141, 'Thị xã Quảng Yên', '206', 'Thị xã', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (142, 'Huyện Cô Tô', '207', 'Huyện', '22');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (143, 'Thành phố Bắc Giang', '213', 'Thành phố', '24');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (144, 'Huyện Yên Thế', '215', 'Huyện', '24');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (145, 'Huyện Tân Yên', '216', 'Huyện', '24');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (146, 'Huyện Lạng Giang', '217', 'Huyện', '24');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (147, 'Huyện Lục Nam', '218', 'Huyện', '24');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (148, 'Huyện Lục Ngạn', '219', 'Huyện', '24');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (149, 'Huyện Sơn Động', '220', 'Huyện', '24');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (150, 'Huyện Yên Dũng', '221', 'Huyện', '24');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (151, 'Huyện Việt Yên', '222', 'Huyện', '24');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (152, 'Huyện Hiệp Hòa', '223', 'Huyện', '24');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (153, 'Thành phố Việt Trì', '227', 'Thành phố', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (154, 'Thị xã Phú Thọ', '228', 'Thị xã', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (155, 'Huyện Đoan Hùng', '230', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (156, 'Huyện Hạ Hoà', '231', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (157, 'Huyện Thanh Ba', '232', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (158, 'Huyện Phù Ninh', '233', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (159, 'Huyện Yên Lập', '234', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (160, 'Huyện Cẩm Khê', '235', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (161, 'Huyện Tam Nông', '236', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (162, 'Huyện Lâm Thao', '237', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (163, 'Huyện Thanh Sơn', '238', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (164, 'Huyện Thanh Thuỷ', '239', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (165, 'Huyện Tân Sơn', '240', 'Huyện', '25');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (166, 'Thành phố Vĩnh Yên', '243', 'Thành phố', '26');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (167, 'Thành phố Phúc Yên', '244', 'Thành phố', '26');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (168, 'Huyện Lập Thạch', '246', 'Huyện', '26');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (169, 'Huyện Tam Dương', '247', 'Huyện', '26');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (170, 'Huyện Tam Đảo', '248', 'Huyện', '26');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (171, 'Huyện Bình Xuyên', '249', 'Huyện', '26');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (172, 'Huyện Mê Linh', '250', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (173, 'Huyện Yên Lạc', '251', 'Huyện', '26');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (174, 'Huyện Vĩnh Tường', '252', 'Huyện', '26');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (175, 'Huyện Sông Lô', '253', 'Huyện', '26');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (176, 'Thành phố Bắc Ninh', '256', 'Thành phố', '27');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (177, 'Huyện Yên Phong', '258', 'Huyện', '27');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (178, 'Huyện Quế Võ', '259', 'Huyện', '27');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (179, 'Huyện Tiên Du', '260', 'Huyện', '27');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (180, 'Thị xã Từ Sơn', '261', 'Thị xã', '27');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (181, 'Huyện Thuận Thành', '262', 'Huyện', '27');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (182, 'Huyện Gia Bình', '263', 'Huyện', '27');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (183, 'Huyện Lương Tài', '264', 'Huyện', '27');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (184, 'Quận Hà Đông', '268', 'Quận', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (185, 'Thị xã Sơn Tây', '269', 'Thị xã', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (186, 'Huyện Ba Vì', '271', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (187, 'Huyện Phúc Thọ', '272', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (188, 'Huyện Đan Phượng', '273', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (189, 'Huyện Hoài Đức', '274', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (190, 'Huyện Quốc Oai', '275', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (191, 'Huyện Thạch Thất', '276', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (192, 'Huyện Chương Mỹ', '277', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (193, 'Huyện Thanh Oai', '278', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (194, 'Huyện Thường Tín', '279', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (195, 'Huyện Phú Xuyên', '280', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (196, 'Huyện Ứng Hòa', '281', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (197, 'Huyện Mỹ Đức', '282', 'Huyện', '01');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (198, 'Thành phố Hải Dương', '288', 'Thành phố', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (199, 'Thành phố Chí Linh', '290', 'Thành phố', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (200, 'Huyện Nam Sách', '291', 'Huyện', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (201, 'Thị xã Kinh Môn', '292', 'Thị xã', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (202, 'Huyện Kim Thành', '293', 'Huyện', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (203, 'Huyện Thanh Hà', '294', 'Huyện', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (204, 'Huyện Cẩm Giàng', '295', 'Huyện', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (205, 'Huyện Bình Giang', '296', 'Huyện', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (206, 'Huyện Gia Lộc', '297', 'Huyện', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (207, 'Huyện Tứ Kỳ', '298', 'Huyện', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (208, 'Huyện Ninh Giang', '299', 'Huyện', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (209, 'Huyện Thanh Miện', '300', 'Huyện', '30');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (210, 'Quận Hồng Bàng', '303', 'Quận', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (211, 'Quận Ngô Quyền', '304', 'Quận', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (212, 'Quận Lê Chân', '305', 'Quận', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (213, 'Quận Hải An', '306', 'Quận', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (214, 'Quận Kiến An', '307', 'Quận', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (215, 'Quận Đồ Sơn', '308', 'Quận', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (216, 'Quận Dương Kinh', '309', 'Quận', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (217, 'Huyện Thuỷ Nguyên', '311', 'Huyện', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (218, 'Huyện An Dương', '312', 'Huyện', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (219, 'Huyện An Lão', '313', 'Huyện', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (220, 'Huyện Kiến Thuỵ', '314', 'Huyện', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (221, 'Huyện Tiên Lãng', '315', 'Huyện', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (222, 'Huyện Vĩnh Bảo', '316', 'Huyện', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (223, 'Huyện Cát Hải', '317', 'Huyện', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (224, 'Huyện Bạch Long Vĩ', '318', 'Huyện', '31');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (225, 'Thành phố Hưng Yên', '323', 'Thành phố', '33');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (226, 'Huyện Văn Lâm', '325', 'Huyện', '33');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (227, 'Huyện Văn Giang', '326', 'Huyện', '33');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (228, 'Huyện Yên Mỹ', '327', 'Huyện', '33');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (229, 'Thị xã Mỹ Hào', '328', 'Thị xã', '33');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (230, 'Huyện Ân Thi', '329', 'Huyện', '33');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (231, 'Huyện Khoái Châu', '330', 'Huyện', '33');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (232, 'Huyện Kim Động', '331', 'Huyện', '33');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (233, 'Huyện Tiên Lữ', '332', 'Huyện', '33');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (234, 'Huyện Phù Cừ', '333', 'Huyện', '33');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (235, 'Thành phố Thái Bình', '336', 'Thành phố', '34');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (236, 'Huyện Quỳnh Phụ', '338', 'Huyện', '34');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (237, 'Huyện Hưng Hà', '339', 'Huyện', '34');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (238, 'Huyện Đông Hưng', '340', 'Huyện', '34');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (239, 'Huyện Thái Thụy', '341', 'Huyện', '34');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (240, 'Huyện Tiền Hải', '342', 'Huyện', '34');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (241, 'Huyện Kiến Xương', '343', 'Huyện', '34');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (242, 'Huyện Vũ Thư', '344', 'Huyện', '34');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (243, 'Thành phố Phủ Lý', '347', 'Thành phố', '35');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (244, 'Thị xã Duy Tiên', '349', 'Thị xã', '35');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (245, 'Huyện Kim Bảng', '350', 'Huyện', '35');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (246, 'Huyện Thanh Liêm', '351', 'Huyện', '35');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (247, 'Huyện Bình Lục', '352', 'Huyện', '35');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (248, 'Huyện Lý Nhân', '353', 'Huyện', '35');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (249, 'Thành phố Nam Định', '356', 'Thành phố', '36');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (250, 'Huyện Mỹ Lộc', '358', 'Huyện', '36');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (251, 'Huyện Vụ Bản', '359', 'Huyện', '36');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (252, 'Huyện Ý Yên', '360', 'Huyện', '36');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (253, 'Huyện Nghĩa Hưng', '361', 'Huyện', '36');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (254, 'Huyện Nam Trực', '362', 'Huyện', '36');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (255, 'Huyện Trực Ninh', '363', 'Huyện', '36');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (256, 'Huyện Xuân Trường', '364', 'Huyện', '36');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (257, 'Huyện Giao Thủy', '365', 'Huyện', '36');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (258, 'Huyện Hải Hậu', '366', 'Huyện', '36');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (259, 'Thành phố Ninh Bình', '369', 'Thành phố', '37');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (260, 'Thành phố Tam Điệp', '370', 'Thành phố', '37');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (261, 'Huyện Nho Quan', '372', 'Huyện', '37');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (262, 'Huyện Gia Viễn', '373', 'Huyện', '37');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (263, 'Huyện Hoa Lư', '374', 'Huyện', '37');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (264, 'Huyện Yên Khánh', '375', 'Huyện', '37');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (265, 'Huyện Kim Sơn', '376', 'Huyện', '37');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (266, 'Huyện Yên Mô', '377', 'Huyện', '37');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (267, 'Thành phố Thanh Hóa', '380', 'Thành phố', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (268, 'Thị xã Bỉm Sơn', '381', 'Thị xã', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (269, 'Thành phố Sầm Sơn', '382', 'Thành phố', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (270, 'Huyện Mường Lát', '384', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (271, 'Huyện Quan Hóa', '385', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (272, 'Huyện Bá Thước', '386', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (273, 'Huyện Quan Sơn', '387', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (274, 'Huyện Lang Chánh', '388', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (275, 'Huyện Ngọc Lặc', '389', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (276, 'Huyện Cẩm Thủy', '390', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (277, 'Huyện Thạch Thành', '391', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (278, 'Huyện Hà Trung', '392', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (279, 'Huyện Vĩnh Lộc', '393', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (280, 'Huyện Yên Định', '394', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (281, 'Huyện Thọ Xuân', '395', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (282, 'Huyện Thường Xuân', '396', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (283, 'Huyện Triệu Sơn', '397', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (284, 'Huyện Thiệu Hóa', '398', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (285, 'Huyện Hoằng Hóa', '399', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (286, 'Huyện Hậu Lộc', '400', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (287, 'Huyện Nga Sơn', '401', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (288, 'Huyện Như Xuân', '402', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (289, 'Huyện Như Thanh', '403', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (290, 'Huyện Nông Cống', '404', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (291, 'Huyện Đông Sơn', '405', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (292, 'Huyện Quảng Xương', '406', 'Huyện', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (293, 'Thị xã Nghi Sơn', '407', 'Thị xã', '38');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (294, 'Thành phố Vinh', '412', 'Thành phố', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (295, 'Thị xã Cửa Lò', '413', 'Thị xã', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (296, 'Thị xã Thái Hoà', '414', 'Thị xã', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (297, 'Huyện Quế Phong', '415', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (298, 'Huyện Quỳ Châu', '416', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (299, 'Huyện Kỳ Sơn', '417', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (300, 'Huyện Tương Dương', '418', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (301, 'Huyện Nghĩa Đàn', '419', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (302, 'Huyện Quỳ Hợp', '420', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (303, 'Huyện Quỳnh Lưu', '421', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (304, 'Huyện Con Cuông', '422', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (305, 'Huyện Tân Kỳ', '423', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (306, 'Huyện Anh Sơn', '424', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (307, 'Huyện Diễn Châu', '425', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (308, 'Huyện Yên Thành', '426', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (309, 'Huyện Đô Lương', '427', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (310, 'Huyện Thanh Chương', '428', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (311, 'Huyện Nghi Lộc', '429', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (312, 'Huyện Nam Đàn', '430', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (313, 'Huyện Hưng Nguyên', '431', 'Huyện', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (314, 'Thị xã Hoàng Mai', '432', 'Thị xã', '40');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (315, 'Thành phố Hà Tĩnh', '436', 'Thành phố', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (316, 'Thị xã Hồng Lĩnh', '437', 'Thị xã', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (317, 'Huyện Hương Sơn', '439', 'Huyện', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (318, 'Huyện Đức Thọ', '440', 'Huyện', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (319, 'Huyện Vũ Quang', '441', 'Huyện', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (320, 'Huyện Nghi Xuân', '442', 'Huyện', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (321, 'Huyện Can Lộc', '443', 'Huyện', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (322, 'Huyện Hương Khê', '444', 'Huyện', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (323, 'Huyện Thạch Hà', '445', 'Huyện', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (324, 'Huyện Cẩm Xuyên', '446', 'Huyện', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (325, 'Huyện Kỳ Anh', '447', 'Huyện', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (326, 'Huyện Lộc Hà', '448', 'Huyện', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (327, 'Thị xã Kỳ Anh', '449', 'Thị xã', '42');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (328, 'Thành Phố Đồng Hới', '450', 'Thành phố', '44');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (329, 'Huyện Minh Hóa', '452', 'Huyện', '44');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (330, 'Huyện Tuyên Hóa', '453', 'Huyện', '44');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (331, 'Huyện Quảng Trạch', '454', 'Huyện', '44');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (332, 'Huyện Bố Trạch', '455', 'Huyện', '44');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (333, 'Huyện Quảng Ninh', '456', 'Huyện', '44');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (334, 'Huyện Lệ Thủy', '457', 'Huyện', '44');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (335, 'Thị xã Ba Đồn', '458', 'Thị xã', '44');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (336, 'Thành phố Đông Hà', '461', 'Thành phố', '45');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (337, 'Thị xã Quảng Trị', '462', 'Thị xã', '45');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (338, 'Huyện Vĩnh Linh', '464', 'Huyện', '45');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (339, 'Huyện Hướng Hóa', '465', 'Huyện', '45');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (340, 'Huyện Gio Linh', '466', 'Huyện', '45');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (341, 'Huyện Đa Krông', '467', 'Huyện', '45');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (342, 'Huyện Cam Lộ', '468', 'Huyện', '45');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (343, 'Huyện Triệu Phong', '469', 'Huyện', '45');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (344, 'Huyện Hải Lăng', '470', 'Huyện', '45');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (345, 'Huyện Cồn Cỏ', '471', 'Huyện', '45');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (346, 'Thành phố Huế', '474', 'Thành phố', '46');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (347, 'Huyện Phong Điền', '476', 'Huyện', '46');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (348, 'Huyện Quảng Điền', '477', 'Huyện', '46');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (349, 'Huyện Phú Vang', '478', 'Huyện', '46');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (350, 'Thị xã Hương Thủy', '479', 'Thị xã', '46');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (351, 'Thị xã Hương Trà', '480', 'Thị xã', '46');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (352, 'Huyện A Lưới', '481', 'Huyện', '46');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (353, 'Huyện Phú Lộc', '482', 'Huyện', '46');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (354, 'Huyện Nam Đông', '483', 'Huyện', '46');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (355, 'Quận Liên Chiểu', '490', 'Quận', '48');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (356, 'Quận Thanh Khê', '491', 'Quận', '48');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (357, 'Quận Hải Châu', '492', 'Quận', '48');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (358, 'Quận Sơn Trà', '493', 'Quận', '48');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (359, 'Quận Ngũ Hành Sơn', '494', 'Quận', '48');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (360, 'Quận Cẩm Lệ', '495', 'Quận', '48');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (361, 'Huyện Hòa Vang', '497', 'Huyện', '48');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (362, 'Huyện Hoàng Sa', '498', 'Huyện', '48');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (363, 'Thành phố Tam Kỳ', '502', 'Thành phố', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (364, 'Thành phố Hội An', '503', 'Thành phố', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (365, 'Huyện Tây Giang', '504', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (366, 'Huyện Đông Giang', '505', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (367, 'Huyện Đại Lộc', '506', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (368, 'Thị xã Điện Bàn', '507', 'Thị xã', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (369, 'Huyện Duy Xuyên', '508', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (370, 'Huyện Quế Sơn', '509', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (371, 'Huyện Nam Giang', '510', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (372, 'Huyện Phước Sơn', '511', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (373, 'Huyện Hiệp Đức', '512', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (374, 'Huyện Thăng Bình', '513', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (375, 'Huyện Tiên Phước', '514', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (376, 'Huyện Bắc Trà My', '515', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (377, 'Huyện Nam Trà My', '516', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (378, 'Huyện Núi Thành', '517', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (379, 'Huyện Phú Ninh', '518', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (380, 'Huyện Nông Sơn', '519', 'Huyện', '49');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (381, 'Thành phố Quảng Ngãi', '522', 'Thành phố', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (382, 'Huyện Bình Sơn', '524', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (383, 'Huyện Trà Bồng', '525', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (384, 'Huyện Sơn Tịnh', '527', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (385, 'Huyện Tư Nghĩa', '528', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (386, 'Huyện Sơn Hà', '529', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (387, 'Huyện Sơn Tây', '530', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (388, 'Huyện Minh Long', '531', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (389, 'Huyện Nghĩa Hành', '532', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (390, 'Huyện Mộ Đức', '533', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (391, 'Thị xã Đức Phổ', '534', 'Thị xã', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (392, 'Huyện Ba Tơ', '535', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (393, 'Huyện Lý Sơn', '536', 'Huyện', '51');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (394, 'Thành phố Qui Nhơn', '540', 'Thành phố', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (395, 'Huyện An Lão', '542', 'Huyện', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (396, 'Thị xã Hoài Nhơn', '543', 'Thị xã', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (397, 'Huyện Hoài Ân', '544', 'Huyện', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (398, 'Huyện Phù Mỹ', '545', 'Huyện', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (399, 'Huyện Vĩnh Thạnh', '546', 'Huyện', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (400, 'Huyện Tây Sơn', '547', 'Huyện', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (401, 'Huyện Phù Cát', '548', 'Huyện', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (402, 'Thị xã An Nhơn', '549', 'Thị xã', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (403, 'Huyện Tuy Phước', '550', 'Huyện', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (404, 'Huyện Vân Canh', '551', 'Huyện', '52');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (405, 'Thành phố Tuy Hoà', '555', 'Thành phố', '54');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (406, 'Thị xã Sông Cầu', '557', 'Thị xã', '54');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (407, 'Huyện Đồng Xuân', '558', 'Huyện', '54');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (408, 'Huyện Tuy An', '559', 'Huyện', '54');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (409, 'Huyện Sơn Hòa', '560', 'Huyện', '54');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (410, 'Huyện Sông Hinh', '561', 'Huyện', '54');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (411, 'Huyện Tây Hoà', '562', 'Huyện', '54');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (412, 'Huyện Phú Hoà', '563', 'Huyện', '54');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (413, 'Thị xã Đông Hòa', '564', 'Thị xã', '54');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (414, 'Thành phố Nha Trang', '568', 'Thành phố', '56');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (415, 'Thành phố Cam Ranh', '569', 'Thành phố', '56');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (416, 'Huyện Cam Lâm', '570', 'Huyện', '56');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (417, 'Huyện Vạn Ninh', '571', 'Huyện', '56');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (418, 'Thị xã Ninh Hòa', '572', 'Thị xã', '56');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (419, 'Huyện Khánh Vĩnh', '573', 'Huyện', '56');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (420, 'Huyện Diên Khánh', '574', 'Huyện', '56');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (421, 'Huyện Khánh Sơn', '575', 'Huyện', '56');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (422, 'Huyện Trường Sa', '576', 'Huyện', '56');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (423, 'Thành phố Phan Rang-Tháp Chàm', '582', 'Thành phố', '58');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (424, 'Huyện Bác Ái', '584', 'Huyện', '58');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (425, 'Huyện Ninh Sơn', '585', 'Huyện', '58');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (426, 'Huyện Ninh Hải', '586', 'Huyện', '58');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (427, 'Huyện Ninh Phước', '587', 'Huyện', '58');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (428, 'Huyện Thuận Bắc', '588', 'Huyện', '58');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (429, 'Huyện Thuận Nam', '589', 'Huyện', '58');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (430, 'Thành phố Phan Thiết', '593', 'Thành phố', '60');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (431, 'Thị xã La Gi', '594', 'Thị xã', '60');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (432, 'Huyện Tuy Phong', '595', 'Huyện', '60');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (433, 'Huyện Bắc Bình', '596', 'Huyện', '60');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (434, 'Huyện Hàm Thuận Bắc', '597', 'Huyện', '60');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (435, 'Huyện Hàm Thuận Nam', '598', 'Huyện', '60');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (436, 'Huyện Tánh Linh', '599', 'Huyện', '60');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (437, 'Huyện Đức Linh', '600', 'Huyện', '60');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (438, 'Huyện Hàm Tân', '601', 'Huyện', '60');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (439, 'Huyện Phú Quí', '602', 'Huyện', '60');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (440, 'Thành phố Kon Tum', '608', 'Thành phố', '62');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (441, 'Huyện Đắk Glei', '610', 'Huyện', '62');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (442, 'Huyện Ngọc Hồi', '611', 'Huyện', '62');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (443, 'Huyện Đắk Tô', '612', 'Huyện', '62');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (444, 'Huyện Kon Plông', '613', 'Huyện', '62');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (445, 'Huyện Kon Rẫy', '614', 'Huyện', '62');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (446, 'Huyện Đắk Hà', '615', 'Huyện', '62');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (447, 'Huyện Sa Thầy', '616', 'Huyện', '62');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (448, 'Huyện Tu Mơ Rông', '617', 'Huyện', '62');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (449, 'Huyện Ia H'' Drai', '618', 'Huyện', '62');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (450, 'Thành phố Pleiku', '622', 'Thành phố', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (451, 'Thị xã An Khê', '623', 'Thị xã', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (452, 'Thị xã Ayun Pa', '624', 'Thị xã', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (453, 'Huyện KBang', '625', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (454, 'Huyện Đăk Đoa', '626', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (455, 'Huyện Chư Păh', '627', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (456, 'Huyện Ia Grai', '628', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (457, 'Huyện Mang Yang', '629', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (458, 'Huyện Kông Chro', '630', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (459, 'Huyện Đức Cơ', '631', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (460, 'Huyện Chư Prông', '632', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (461, 'Huyện Chư Sê', '633', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (462, 'Huyện Đăk Pơ', '634', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (463, 'Huyện Ia Pa', '635', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (464, 'Huyện Krông Pa', '637', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (465, 'Huyện Phú Thiện', '638', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (466, 'Huyện Chư Pưh', '639', 'Huyện', '64');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (467, 'Thành phố Buôn Ma Thuột', '643', 'Thành phố', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (468, 'Thị Xã Buôn Hồ', '644', 'Thị xã', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (469, 'Huyện Ea H''leo', '645', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (470, 'Huyện Ea Súp', '646', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (471, 'Huyện Buôn Đôn', '647', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (472, 'Huyện Cư M''gar', '648', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (473, 'Huyện Krông Búk', '649', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (474, 'Huyện Krông Năng', '650', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (475, 'Huyện Ea Kar', '651', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (476, 'Huyện M''Đrắk', '652', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (477, 'Huyện Krông Bông', '653', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (478, 'Huyện Krông Pắc', '654', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (479, 'Huyện Krông A Na', '655', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (480, 'Huyện Lắk', '656', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (481, 'Huyện Cư Kuin', '657', 'Huyện', '66');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (482, 'Thành phố Gia Nghĩa', '660', 'Thành phố', '67');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (483, 'Huyện Đăk Glong', '661', 'Huyện', '67');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (484, 'Huyện Cư Jút', '662', 'Huyện', '67');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (485, 'Huyện Đắk Mil', '663', 'Huyện', '67');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (486, 'Huyện Krông Nô', '664', 'Huyện', '67');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (487, 'Huyện Đắk Song', '665', 'Huyện', '67');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (488, 'Huyện Đắk R''Lấp', '666', 'Huyện', '67');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (489, 'Huyện Tuy Đức', '667', 'Huyện', '67');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (490, 'Thành phố Đà Lạt', '672', 'Thành phố', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (491, 'Thành phố Bảo Lộc', '673', 'Thành phố', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (492, 'Huyện Đam Rông', '674', 'Huyện', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (493, 'Huyện Lạc Dương', '675', 'Huyện', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (494, 'Huyện Lâm Hà', '676', 'Huyện', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (495, 'Huyện Đơn Dương', '677', 'Huyện', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (496, 'Huyện Đức Trọng', '678', 'Huyện', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (497, 'Huyện Di Linh', '679', 'Huyện', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (498, 'Huyện Bảo Lâm', '680', 'Huyện', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (499, 'Huyện Đạ Huoai', '681', 'Huyện', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (500, 'Huyện Đạ Tẻh', '682', 'Huyện', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (501, 'Huyện Cát Tiên', '683', 'Huyện', '68');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (502, 'Thị xã Phước Long', '688', 'Thị xã', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (503, 'Thành phố Đồng Xoài', '689', 'Thành phố', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (504, 'Thị xã Bình Long', '690', 'Thị xã', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (505, 'Huyện Bù Gia Mập', '691', 'Huyện', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (506, 'Huyện Lộc Ninh', '692', 'Huyện', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (507, 'Huyện Bù Đốp', '693', 'Huyện', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (508, 'Huyện Hớn Quản', '694', 'Huyện', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (509, 'Huyện Đồng Phú', '695', 'Huyện', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (510, 'Huyện Bù Đăng', '696', 'Huyện', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (511, 'Huyện Chơn Thành', '697', 'Huyện', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (512, 'Huyện Phú Riềng', '698', 'Huyện', '70');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (513, 'Thành phố Tây Ninh', '703', 'Thành phố', '72');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (514, 'Huyện Tân Biên', '705', 'Huyện', '72');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (515, 'Huyện Tân Châu', '706', 'Huyện', '72');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (516, 'Huyện Dương Minh Châu', '707', 'Huyện', '72');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (517, 'Huyện Châu Thành', '708', 'Huyện', '72');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (518, 'Thị xã Hòa Thành', '709', 'Thị xã', '72');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (519, 'Huyện Gò Dầu', '710', 'Huyện', '72');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (520, 'Huyện Bến Cầu', '711', 'Huyện', '72');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (521, 'Thị xã Trảng Bàng', '712', 'Thị xã', '72');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (522, 'Thành phố Thủ Dầu Một', '718', 'Thành phố', '74');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (523, 'Huyện Bàu Bàng', '719', 'Huyện', '74');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (524, 'Huyện Dầu Tiếng', '720', 'Huyện', '74');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (525, 'Thị xã Bến Cát', '721', 'Thị xã', '74');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (526, 'Huyện Phú Giáo', '722', 'Huyện', '74');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (527, 'Thị xã Tân Uyên', '723', 'Thị xã', '74');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (528, 'Thành phố Dĩ An', '724', 'Thành phố', '74');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (529, 'Thành phố Thuận An', '725', 'Thành phố', '74');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (530, 'Huyện Bắc Tân Uyên', '726', 'Huyện', '74');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (531, 'Thành phố Biên Hòa', '731', 'Thành phố', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (532, 'Thành phố Long Khánh', '732', 'Thành phố', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (533, 'Huyện Tân Phú', '734', 'Huyện', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (534, 'Huyện Vĩnh Cửu', '735', 'Huyện', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (535, 'Huyện Định Quán', '736', 'Huyện', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (536, 'Huyện Trảng Bom', '737', 'Huyện', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (537, 'Huyện Thống Nhất', '738', 'Huyện', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (538, 'Huyện Cẩm Mỹ', '739', 'Huyện', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (539, 'Huyện Long Thành', '740', 'Huyện', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (540, 'Huyện Xuân Lộc', '741', 'Huyện', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (541, 'Huyện Nhơn Trạch', '742', 'Huyện', '75');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (542, 'Thành phố Vũng Tàu', '747', 'Thành phố', '77');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (543, 'Thành phố Bà Rịa', '748', 'Thành phố', '77');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (544, 'Huyện Châu Đức', '750', 'Huyện', '77');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (545, 'Huyện Xuyên Mộc', '751', 'Huyện', '77');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (546, 'Huyện Long Điền', '752', 'Huyện', '77');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (547, 'Huyện Đất Đỏ', '753', 'Huyện', '77');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (548, 'Thị xã Phú Mỹ', '754', 'Thị xã', '77');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (549, 'Huyện Côn Đảo', '755', 'Huyện', '77');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (550, 'Quận 1', '760', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (551, 'Quận 12', '761', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (552, 'Quận Thủ Đức', '762', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (553, 'Quận 9', '763', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (554, 'Quận Gò Vấp', '764', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (555, 'Quận Bình Thạnh', '765', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (556, 'Quận Tân Bình', '766', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (557, 'Quận Tân Phú', '767', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (558, 'Quận Phú Nhuận', '768', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (559, 'Quận 2', '769', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (560, 'Quận 3', '770', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (561, 'Quận 10', '771', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (562, 'Quận 11', '772', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (563, 'Quận 4', '773', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (564, 'Quận 5', '774', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (565, 'Quận 6', '775', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (566, 'Quận 8', '776', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (567, 'Quận Bình Tân', '777', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (568, 'Quận 7', '778', 'Quận', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (569, 'Huyện Củ Chi', '783', 'Huyện', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (570, 'Huyện Hóc Môn', '784', 'Huyện', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (571, 'Huyện Bình Chánh', '785', 'Huyện', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (572, 'Huyện Nhà Bè', '786', 'Huyện', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (573, 'Huyện Cần Giờ', '787', 'Huyện', '79');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (574, 'Thành phố Tân An', '794', 'Thành phố', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (575, 'Thị xã Kiến Tường', '795', 'Thị xã', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (576, 'Huyện Tân Hưng', '796', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (577, 'Huyện Vĩnh Hưng', '797', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (578, 'Huyện Mộc Hóa', '798', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (579, 'Huyện Tân Thạnh', '799', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (580, 'Huyện Thạnh Hóa', '800', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (581, 'Huyện Đức Huệ', '801', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (582, 'Huyện Đức Hòa', '802', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (583, 'Huyện Bến Lức', '803', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (584, 'Huyện Thủ Thừa', '804', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (585, 'Huyện Tân Trụ', '805', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (586, 'Huyện Cần Đước', '806', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (587, 'Huyện Cần Giuộc', '807', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (588, 'Huyện Châu Thành', '808', 'Huyện', '80');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (589, 'Thành phố Mỹ Tho', '815', 'Thành phố', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (590, 'Thị xã Gò Công', '816', 'Thị xã', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (591, 'Thị xã Cai Lậy', '817', 'Thị xã', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (592, 'Huyện Tân Phước', '818', 'Huyện', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (593, 'Huyện Cái Bè', '819', 'Huyện', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (594, 'Huyện Cai Lậy', '820', 'Huyện', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (595, 'Huyện Châu Thành', '821', 'Huyện', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (596, 'Huyện Chợ Gạo', '822', 'Huyện', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (597, 'Huyện Gò Công Tây', '823', 'Huyện', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (598, 'Huyện Gò Công Đông', '824', 'Huyện', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (599, 'Huyện Tân Phú Đông', '825', 'Huyện', '82');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (600, 'Thành phố Bến Tre', '829', 'Thành phố', '83');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (601, 'Huyện Châu Thành', '831', 'Huyện', '83');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (602, 'Huyện Chợ Lách', '832', 'Huyện', '83');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (603, 'Huyện Mỏ Cày Nam', '833', 'Huyện', '83');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (604, 'Huyện Giồng Trôm', '834', 'Huyện', '83');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (605, 'Huyện Bình Đại', '835', 'Huyện', '83');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (606, 'Huyện Ba Tri', '836', 'Huyện', '83');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (607, 'Huyện Thạnh Phú', '837', 'Huyện', '83');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (608, 'Huyện Mỏ Cày Bắc', '838', 'Huyện', '83');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (609, 'Thành phố Trà Vinh', '842', 'Thành phố', '84');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (610, 'Huyện Càng Long', '844', 'Huyện', '84');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (611, 'Huyện Cầu Kè', '845', 'Huyện', '84');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (612, 'Huyện Tiểu Cần', '846', 'Huyện', '84');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (613, 'Huyện Châu Thành', '847', 'Huyện', '84');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (614, 'Huyện Cầu Ngang', '848', 'Huyện', '84');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (615, 'Huyện Trà Cú', '849', 'Huyện', '84');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (616, 'Huyện Duyên Hải', '850', 'Huyện', '84');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (617, 'Thị xã Duyên Hải', '851', 'Thị xã', '84');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (618, 'Thành phố Vĩnh Long', '855', 'Thành phố', '86');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (619, 'Huyện Long Hồ', '857', 'Huyện', '86');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (620, 'Huyện Mang Thít', '858', 'Huyện', '86');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (621, 'Huyện  Vũng Liêm', '859', 'Huyện', '86');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (622, 'Huyện Tam Bình', '860', 'Huyện', '86');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (623, 'Thị xã Bình Minh', '861', 'Thị xã', '86');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (624, 'Huyện Trà Ôn', '862', 'Huyện', '86');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (625, 'Huyện Bình Tân', '863', 'Huyện', '86');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (626, 'Thành phố Cao Lãnh', '866', 'Thành phố', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (627, 'Thành phố Sa Đéc', '867', 'Thành phố', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (628, 'Thị xã Hồng Ngự', '868', 'Thị xã', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (629, 'Huyện Tân Hồng', '869', 'Huyện', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (630, 'Huyện Hồng Ngự', '870', 'Huyện', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (631, 'Huyện Tam Nông', '871', 'Huyện', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (632, 'Huyện Tháp Mười', '872', 'Huyện', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (633, 'Huyện Cao Lãnh', '873', 'Huyện', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (634, 'Huyện Thanh Bình', '874', 'Huyện', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (635, 'Huyện Lấp Vò', '875', 'Huyện', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (636, 'Huyện Lai Vung', '876', 'Huyện', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (637, 'Huyện Châu Thành', '877', 'Huyện', '87');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (638, 'Thành phố Long Xuyên', '883', 'Thành phố', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (639, 'Thành phố Châu Đốc', '884', 'Thành phố', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (640, 'Huyện An Phú', '886', 'Huyện', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (641, 'Thị xã Tân Châu', '887', 'Thị xã', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (642, 'Huyện Phú Tân', '888', 'Huyện', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (643, 'Huyện Châu Phú', '889', 'Huyện', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (644, 'Huyện Tịnh Biên', '890', 'Huyện', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (645, 'Huyện Tri Tôn', '891', 'Huyện', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (646, 'Huyện Châu Thành', '892', 'Huyện', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (647, 'Huyện Chợ Mới', '893', 'Huyện', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (648, 'Huyện Thoại Sơn', '894', 'Huyện', '89');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (649, 'Thành phố Rạch Giá', '899', 'Thành phố', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (650, 'Thành phố Hà Tiên', '900', 'Thành phố', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (651, 'Huyện Kiên Lương', '902', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (652, 'Huyện Hòn Đất', '903', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (653, 'Huyện Tân Hiệp', '904', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (654, 'Huyện Châu Thành', '905', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (655, 'Huyện Giồng Riềng', '906', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (656, 'Huyện Gò Quao', '907', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (657, 'Huyện An Biên', '908', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (658, 'Huyện An Minh', '909', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (659, 'Huyện Vĩnh Thuận', '910', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (660, 'Huyện Phú Quốc', '911', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (661, 'Huyện Kiên Hải', '912', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (662, 'Huyện U Minh Thượng', '913', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (663, 'Huyện Giang Thành', '914', 'Huyện', '91');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (664, 'Quận Ninh Kiều', '916', 'Quận', '92');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (665, 'Quận Ô Môn', '917', 'Quận', '92');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (666, 'Quận Bình Thuỷ', '918', 'Quận', '92');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (667, 'Quận Cái Răng', '919', 'Quận', '92');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (668, 'Quận Thốt Nốt', '923', 'Quận', '92');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (669, 'Huyện Vĩnh Thạnh', '924', 'Huyện', '92');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (670, 'Huyện Cờ Đỏ', '925', 'Huyện', '92');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (671, 'Huyện Phong Điền', '926', 'Huyện', '92');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (672, 'Huyện Thới Lai', '927', 'Huyện', '92');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (673, 'Thành phố Vị Thanh', '930', 'Thành phố', '93');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (674, 'Thành phố Ngã Bảy', '931', 'Thành phố', '93');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (675, 'Huyện Châu Thành A', '932', 'Huyện', '93');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (676, 'Huyện Châu Thành', '933', 'Huyện', '93');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (677, 'Huyện Phụng Hiệp', '934', 'Huyện', '93');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (678, 'Huyện Vị Thuỷ', '935', 'Huyện', '93');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (679, 'Huyện Long Mỹ', '936', 'Huyện', '93');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (680, 'Thị xã Long Mỹ', '937', 'Thị xã', '93');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (681, 'Thành phố Sóc Trăng', '941', 'Thành phố', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (682, 'Huyện Châu Thành', '942', 'Huyện', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (683, 'Huyện Kế Sách', '943', 'Huyện', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (684, 'Huyện Mỹ Tú', '944', 'Huyện', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (685, 'Huyện Cù Lao Dung', '945', 'Huyện', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (686, 'Huyện Long Phú', '946', 'Huyện', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (687, 'Huyện Mỹ Xuyên', '947', 'Huyện', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (688, 'Thị xã Ngã Năm', '948', 'Thị xã', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (689, 'Huyện Thạnh Trị', '949', 'Huyện', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (690, 'Thị xã Vĩnh Châu', '950', 'Thị xã', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (691, 'Huyện Trần Đề', '951', 'Huyện', '94');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (692, 'Thành phố Bạc Liêu', '954', 'Thành phố', '95');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (693, 'Huyện Hồng Dân', '956', 'Huyện', '95');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (694, 'Huyện Phước Long', '957', 'Huyện', '95');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (695, 'Huyện Vĩnh Lợi', '958', 'Huyện', '95');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (696, 'Thị xã Giá Rai', '959', 'Thị xã', '95');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (697, 'Huyện Đông Hải', '960', 'Huyện', '95');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (698, 'Huyện Hoà Bình', '961', 'Huyện', '95');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (699, 'Thành phố Cà Mau', '964', 'Thành phố', '96');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (700, 'Huyện U Minh', '966', 'Huyện', '96');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (701, 'Huyện Thới Bình', '967', 'Huyện', '96');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (702, 'Huyện Trần Văn Thời', '968', 'Huyện', '96');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (703, 'Huyện Cái Nước', '969', 'Huyện', '96');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (704, 'Huyện Đầm Dơi', '970', 'Huyện', '96');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (705, 'Huyện Năm Căn', '971', 'Huyện', '96');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (706, 'Huyện Phú Tân', '972', 'Huyện', '96');
INSERT INTO web_ok.dictrict (ID, NameDictrict, maqh, type, matp) VALUES (707, 'Huyện Ngọc Hiển', '973', 'Huyện', '96');