INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Thành phố Hà Nội', '01', 'Thành phố Trung ương');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Hà Giang', '02', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Cao Bằng', '04', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Bắc Kạn', '06', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Tuyên Quang', '08', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Lào Cai', '10', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Điện Biên', '11', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Lai Châu', '12', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Sơn La', '14', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Yên Bái', '15', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Hoà Bình', '17', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Thái Nguyên', '19', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Lạng Sơn', '20', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Quảng Ninh', '22', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Bắc Giang', '24', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Phú Thọ', '25', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Vĩnh Phúc', '26', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Bắc Ninh', '27', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Hải Dương', '30', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Thành phố Hải Phòng', '31', 'Thành phố Trung ương');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Hưng Yên', '33', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Thái Bình', '34', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Hà Nam', '35', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Nam Định', '36', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Ninh Bình', '37', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Thanh Hóa', '38', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Nghệ An', '40', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Hà Tĩnh', '42', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Quảng Bình', '44', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Quảng Trị', '45', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Thừa Thiên Huế', '46', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Thành phố Đà Nẵng', '48', 'Thành phố Trung ương');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Quảng Nam', '49', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Quảng Ngãi', '51', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Bình Định', '52', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Phú Yên', '54', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Khánh Hòa', '56', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Ninh Thuận', '58', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Bình Thuận', '60', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Kon Tum', '62', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Gia Lai', '64', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Đắk Lắk', '66', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Đắk Nông', '67', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Lâm Đồng', '68', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Bình Phước', '70', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Tây Ninh', '72', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Bình Dương', '74', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Đồng Nai', '75', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Bà Rịa - Vũng Tàu', '77', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Thành phố Hồ Chí Minh', '79', 'Thành phố Trung ương');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Long An', '80', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Tiền Giang', '82', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Bến Tre', '83', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Trà Vinh', '84', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Vĩnh Long', '86', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Đồng Tháp', '87', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh An Giang', '89', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Kiên Giang', '91', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Thành phố Cần Thơ', '92', 'Thành phố Trung ương');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Hậu Giang', '93', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Sóc Trăng', '94', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Bạc Liêu', '95', 'Tỉnh');
INSERT INTO web_ok.province (NameProvince, matp, type) VALUES ('Tỉnh Cà Mau', '96', 'Tỉnh');